require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  NewCops: disable

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"
    - "config/routes.rb"

Metrics/ClassLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Metrics/ParameterLists:
  Enabled: false

Rails:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
