# MOVE OVER TO GITHUB ACTIONS
dist: bionic
language: ruby
cache:
  apt: true
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/
    - node_modules
rvm:
  - 2.5.8
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - sudo apt-get update -qq
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 2
  - sudo apt-get install -yqq nodejs
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - yarn install
  - yarn lint
  - bin/rails assets:precompile
  - yarn es-check
  - bundle install -j $(nproc) --path vendor/bundle
  - bundle exec rubocop
  - bundle exec brakeman -z
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rails db:migrate
  - RAILS_ENV=test bundle exec rails db:seed
  - RAILS_ENV=test bundle exec rspec
