version: '3.7'

services:
  postgres:
    image: 'postgres:14.8-alpine'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=sm
      - POSTGRES_PASSWORD=sm_password
    ports:
      - 5432:5432
  redis-sidekiq:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379
  redis-cache:
    image: redis:5.0.3-alpine
    ports:
      - 6380:6379
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  pgdata:
