default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  template: template0

  # The env var DATABASE_URL always takes precedence.
  # If provided, it MUST contain:
  # - The username and password
  # - The host and port
  # - The name of the database
  #
  # Example:
  # export DATABASE_URL="postgres://user1:supersecretpassword@myhost.com:5432/soulmedicine-production"

  <% if ENV.include? 'DATABASE_URL' %>
  database_url: ENV['DATABASE_URL']
  <% else %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: <%= ENV.fetch('DATABASE_USER') { raise 'DATABASE_USER missing' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { raise 'DATABASE_PASSWORD missing' } %>
  database: <%= ENV.fetch('DATABASE_NAME') { raise 'DATABASE_NAME missing' } %>_<%= Rails.env %>
  <% end %>

development:
  <<: *default

test:
  <<: *default
  # Explicitly set the database name for test
  database: soulmedicine_test

production:
  <<: *default
