default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  template: template0

  # The env var DATABASE_URL always takes precedence and will be used
  # automatically by RAILS.
  # (ref: https://guides.rubyonrails.org/v5.2/configuring.html#connection-preference)
  #
  # Thus, we expect that if DATABASE_URL is provided, it MUST contain:
  # - The username and password
  # - The host and port
  # - The name of the database
  #
  # Example:
  # export DATABASE_URL="postgres://user1:supersecretpassword@myhost.com:5432/soulmedicine-production"

  <% unless ENV.include? 'DATABASE_URL' %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: <%= ENV.fetch('DATABASE_USER') { raise 'DATABASE_USER missing' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { raise 'DATABASE_PASSWORD missing' } %>
  <% end %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { raise 'DATABASE_NAME missing' } %>_development

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { raise 'DATABASE_NAME missing' } %>_test

production:
  <<: *default
