# This workflow opens issues for pull requests opened by dependabot.
# See for more info: https://github.com/actions-cool/issues-helper

name: Open Dependabot Issues # from pull requests

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Create issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.pull_request.title }}
          body: |
            ### Dependabot opened a pull request to update a dependency. Please review it: ${{ github.event.pull_request.html_url }} 
            - [ ] Comment on this issue tagging Chayn staff (@kyleecodes) to be assigned this issue.
            - [ ] Follow directions in the Chayn Dependency Upgrade Guide here: https://chayn.notion.site/Chayn-Tech-Contributor-Wiki-5356c7118c134863a2e092e9df6cbc34?pvs=4
          labels: "dependencies"
